#!/bin/sh

echo "$(date) - $(realpath $0)" >> /var/log/daemon.log

/usr/bin/docker builder prune -af --filter "until=24h" >> /dev/null 2>&1

/usr/bin/docker image prune -af --filter "until=24h" >> /dev/null 2>&1

/usr/bin/docker volume prune -af >> /dev/null 2>&1
