#!/bin/sh

echo "$(date) - $(realpath $0)" >> /var/log/daemon.log

/usr/bin/docker volume prune -f >> /dev/null 2>&1

docker builder prune -af --filter "until=24h" >> /dev/null 2>&1

docker image prune -af --filter "until=24h" >> /dev/null 2>&1
